version: '3.9'

services:
  stable-diffusion-auto-cpu:
    container_name: stable-diffusion-auto-cpu
    build: ./services/AUTOMATIC1111
    image: sd-auto:49
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - ./data:/data
      - ./output:/output
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api
    restart: "no"